[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sender = "0x39b974E540B5EBE88579AC2D2668233C39C964D2"
force = true
ffi = true
ast = true
build-info = true
optimizer = true
auto_detect_remappings = false
optimizer_runs = 999999
evm_version = "london"
bytecode_hash = "ipfs"
extra_output = ["storageLayout"]
extra_output_files = ["metadata"]
fs_permissions = [{ access = "read", path = "out" }]

[rpc_endpoints]
pangolin = "https://pangolin-rpc.darwinia.network"
crab = "https://crab-rpc.darwinia.network"

