[profile.default]
src = "src"
out = "out"
script = "script"
cache = true
cache_path = "cache"
build_info = true
libs = ["lib"]
sender = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
force = false
optimizer = true
verbosity = 5
auto_detect_remappings = false
optimizer_runs = 999999
evm_version = "london"
bytecode_hash = "ipfs"
extra_output = ['storageLayout']
extra_output_files = ["metadata"]

[rpc_endpoints]
## testnets
darwinia_koi = "https://koi-rpc.darwinia.network"

## mainnets
darwinia = "https://darwinia-rpc.itering.io"
crab = "https://crab-rpc.itering.io"
